### ISSUE TITLE
Preview button placement algorithm problems

### ISSUE THREAD

**Issue by awilkins** [Komodo/markdown-viewer#3]
Linux (Ubuntu) with dual monitors

Preview button places correctly :

* If you have a single monitor
* If you run Komodo Edit not-full-screen
* With freshly opened files

If you 

* Use Komodo full screen on the left screen of a dual monitor system
  * Button placed somewhere on right screen
* Resize window
  * Button does not move appropriately with corner of document window
* Change layout (by folding project tray, etc
  * Button does not relocate properly

This is all very confusing when you first install the add on and try it out in a Komodo window running full screen on a dual monitor setup - it appears not to work at all until you notice the button floating on the other screen.

If fixing this is hard, can I suggest that instead of a button, you add an item to the context menu, like the "Browser Preview" option?

**Comment by mpathy** [comment]
+1 to just keep it in the main Toolbar, or even just in the menu - with an convinient keyboard shortcut.
I have exactly the same problems and additionally this floating preview button is inconsistent with the current UI of Komodo Edit.
I will use my own solution based on a macro and Strapdown.js until it is fixed. Strapdown.js looks better by the way, you can easily add some templates to it.
But I keep a eye on the plugin ;)

**Comment by Naatan** [comment]
Markdown viewer has been built-in to Komodo, please ensure you're running Komodo 9.2.1 and uninstall the addon (it overrides the built-in version).
